[package]
name = "learning_gl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
num-derive = "0.4.0"
num-traits = "0.2.16"
gl = "0.14.0"
glfw = "0.51.0"
gl_loader = "0.1.2"
nalgebra-glm = "0.18.0"
russimp = { version = "2.0.5", features = ["prebuilt"] }
# image = "0.24.6"
# clang-sys = "1.6.1"
# bindgen = "0.66.1"
# std140 = "0.2.6"
# spin_sleep = "1.1.1"
# rayon = "1.7.0"
# serde_json = "1.0.99"
# stb = "0.3.2"
