[package]
name = "learning_gl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.51.0"
gl_loader = "0.1.2"
nalgebra-glm = "0.18.0"
clang-sys = "1.6.1"
bindgen = "0.66.1"
russimp = { version = "2.0.5", features = ["prebuilt"] }
# stb = "0.3.2"
